# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

dist: trusty

matrix:
    # Note coverage is run in only one configuration.  Longest build first.
    include:
        - env: PYTHON=3.5 RUN_COVERAGE=yes
        - env: PYTHON=3.4
        - env: PYTHON=2.7

before_install:
    # Install Miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - CONDA_INSTALL="conda install --yes -q"
    # Setup environment
    - conda create -n travisci --yes python=$PYTHON
    - source activate travisci
    # Install llvmdev (separate channel, for now)
    - $CONDA_INSTALL -c numba llvmdev="3.8*"
    # Install enum34 for Python < 3.4
    - if [ $PYTHON \< "3.4" ]; then $CONDA_INSTALL enum34; fi
    # Install dependencies for building the docs
    - $CONDA_INSTALL pip sphinx sphinx_rtd_theme pygments
    # Install dependencies for code coverage (codecov.io)
    - if [ "$RUN_COVERAGE" == "yes" ]; then pip install codecov; fi

install:
    - python setup.py build

script:
    # Ensure that the documentation builds without warnings nor missing references
    - cd $TRAVIS_BUILD_DIR/docs
    - make SPHINXOPTS=-Wn clean html
    # Run test suite
    - cd $TRAVIS_BUILD_DIR
    - python runtests.py -v
    - if [ "$RUN_COVERAGE" == "yes" ]; then coverage run runtests.py; fi

after_success:
    - if [ "$RUN_COVERAGE" == "yes" ]; then codecov; fi

notifications:
    email: false
    flowdock: "cb7bc57e58b3d42f77685f93211c03ab"
    on_success: "change"
    on_failure: "always" # "change"
