# References https://gist.github.com/dan-blanchard/7045057
language: python

#sudo: required
dist: trusty

#addons:
  #apt:
    #sources:
      #- ubuntu-toolchain-r-test
    #packages:
      #- g++-4.8

python:
  - env: PYTHON=2.6
  #- env: PYTHON=2.7
  #- env: PYTHON=3.3
  #- env: PYTHON=3.4
  - env: PYTHON=3.5

before_install:
    # Install Miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - CONDA_INSTALL="conda install --yes -q"
    # Setup environment
    - conda create -n travisci --yes python=$PYTHON
    - source activate travisci
    # Install llvmdev (separate channel, for now)
    - $CONDA_INSTALL -c numba llvmdev="3.6*"
    # Install unittest2 and argparse for Python 2.6
    - if [ $PYTHON == "2.6" ]; then $CONDA_INSTALL unittest2 argparse; fi
    # Install enum34 for Python < 3.4
    - if [ $PYTHON \< "3.4" ]; then $CONDA_INSTALL enum34; fi
    # Install dependencies for building the docs
    - $CONDA_INSTALL pip sphinx sphinx_rtd_theme pygments

install:
    - python setup.py build

script:
    # Ensure that the documentation builds without warnings nor missing references
    - cd $TRAVIS_BUILD_DIR/docs ; make SPHINXOPTS=-Wn clean html
    - cd $TRAVIS_BUILD_DIR; python runtests.py -v

notifications:
  email: false
  flowdock: "cb7bc57e58b3d42f77685f93211c03ab"
  on_success: "change"
  on_failure: "always" # "change"
