# # Numba/llvmlite stack needs an older compiler for backwards compatability.
# c_compiler_version:         # [linux]
#   - 7                       # [linux and (x86_64 or ppc64le)]
#   - 11                      # [linux and aarch64]

# cxx_compiler_version:       # [linux]
#   - 7                       # [linux and (x86_64 or ppc64le)]
#   - 11                      # [linux and aarch64]

# fortran_compiler_version:   # [linux]
#   - 7                       # [linux and (x86_64 or ppc64le)]
#   - 11                      # [linux and aarch64]

c_compiler:              # [win]
  - vs2019               # [win]
cxx_compiler:            # [win]
  - vs2019               # [win]

CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk        # [osx and x86_64]
